getAlby/pkgzap

- src/bin/index.js
> feat: support failures in cli

- src/index.ts
> fix: return if levels=0 without fetching

- src/bin/index.js
> fix: use new getFundingDetails in cli

- src/bin/index.js
> fix: take levels as 1 in cli

- lib/src/index.ts
> chore: remove fs promises

- lib/package.json
- lib/yarn.lock
> chore: package.json fixes

- cli/package.json
- cli/src/bin/index.js
- cli/yarn.lock
> chore: add lib package

- cli/bin/index.js
> chore: add node executable

- lib/src/index.ts
> feat: print current package while analyzing

- cli/bin/index.js
- cli/package.json
- cli/yarn.lock
> task cli fixes

- lib/src/index.ts
> fix: warning message disturbing logs

- package.json
- src/App.jsx
- yarn.lock
adds boost button to landing page
> feat: add boost button

- cli/bin/index.js
> feat: encrypt nwc url

- README.md
- src/App.jsx
- src/index.css
> chore: add lib info in landing page

- cli/bin/index.js
> fix: abort if there are zero deps

- cli/bin/index.js
- src/PackageDetail.jsx
- src/index.css
> feat: add message to promote fund-ln

- cli/bin/index.js
- cli/package.json
- cli/yarn.lock
- lib/package.json
> chore: publish packages under org

- cli/package.json
> chore: update alby-tools

- cli/package.json
> fix: unable to resolve import problem

- src/App.jsx
> fix: link and add video

- package.json
> feat: add cname after build

- src/App.jsx
- src/index.css
> fix: add publish info in landing

- src/App.jsx
> chore: add latest info

- cli/bin/index.js
- cli/package.json
- cli/yarn.lock
Follow up to https://github.com/getAlby/pkgzap/pull/66
- Replaces `enquirer` with well maintained `inquirer`
- Updates pkgzap to new version
- Remove unused packages
- Minor refactoring, using `info` instead of `log`
> chore: update pkgzap and other minor improvements
